Company Org/src/objects/Concretian__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Teamwork_User_Id__c</fullName>
        <label>Teamwork User Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Concretian</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Concretian Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Concretians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Company Org/src/objects/Monthly_Report__c.object
<CustomObject>
    <fields>
        <fullName>Concretian__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Concretian</label>
        <referenceTo>Concretian__c</referenceTo>
        <relationshipLabel>Monthly Reports</relationshipLabel>
        <relationshipName>Monthly_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Monthly Report</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Monthly Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Company Org/src/objects/TeamWork_Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>App_Key__c</fullName>
        <label>App Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Point__c</fullName>
        <label>End Point</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>TeamWork Configuration</label>
</CustomObject>

Company Org/src/objects/Time_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Concretians__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Concretian</label>
        <referenceTo>Concretian__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Monthly_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Monthly Report</label>
        <referenceTo>Monthly_Report__c</referenceTo>
        <relationshipLabel>Time Entries</relationshipLabel>
        <relationshipName>Time_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_Entry_ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>Time Entry ExternalId</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>billable_mins_sum__c</fullName>
        <label>billable-mins-sum</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>non_billable_mins_sum__c</fullName>
        <label>non-billable-mins-sum</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>total_hours_sum__c</fullName>
        <label>total-hours-sum</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>total_mins_sum__c</fullName>
        <label>total-mins-sum</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Time Entry</label>
    <nameField>
        <label>Time Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Company Org/src/classes/SyncTimeEntyBatchJob.cls
global with sharing class SyncTimeEntyBatchJob implements Database.Batchable<sObject>, Database.AllowsCallouts {
    global Database.QueryLocator start(Database.BatchableContext BC){
        delete [select id from Time_Entry__c];
        delete [select id from Monthly_Report__c];
        return Database.getQueryLocator('Select id, Email__c, Teamwork_User_Id__c from Concretian__c Where Teamwork_User_Id__c != null');
    }
    
    global void execute(Database.BatchableContext BC, List<Concretian__c> scope){
       
        HttpRequest req ;
        Http http;
        HTTPResponse res;
        TeamWork_Configuration__c  Configure = TeamWorkConFig.Configuration;
        Date lastday = Date.today().addDays(-1);
        DateTime dt = DateTime.newInstance(lastday.year(), lastday.month(),lastday.day());
        String lastdayStr = dt.format('yyyyMMdd');
        TimeEntry timeEntryDetail;
        String authorizationHeader = EncodingUtil.base64Encode(Blob.valueOf(Configure.App_Key__c));
        Time_Entry__c timeEntryObj;
        List<Time_Entry__c> lstOfTimeEntry = new list<Time_Entry__c>();
        
        for(Concretian__c conObj : scope){
            req = new HttpRequest(); 
            req.setEndpoint(Configure.End_Point__c+'time/total.json?userId='+conObj.Teamwork_User_Id__c+'&fromDate='+lastdayStr+'&toDate='+lastdayStr);
            req.setMethod('GET');
            req.setHeader('Accept', 'application/json; charset=UTF-8');
            req.setHeader('Content-Type','application/json');  
            req.setHeader('Authorization', 'Basic '+authorizationHeader);
            req.setTimeout(120000);
            http = new Http();
            try {
                res = http.send(req);
                if(res.getStatusCode() == 200){
                    timeEntryDetail = TimeEntry.parse(string.valueof(res.getbody()).ReplaceAll('-','_'));
                    if(timeEntryDetail.STATUS == 'OK' && timeEntryDetail.time_totals != null){
                        timeEntryObj = new Time_Entry__c();
                        timeEntryObj.Concretians__c = conObj.Id;
                        timeEntryObj.total_hours_sum__c = Decimal.valueOf(timeEntryDetail.time_totals.total_hours_sum);
                        timeEntryObj.total_mins_sum__c = Decimal.valueOf(timeEntryDetail.time_totals.total_mins_sum);
                        timeEntryObj.billable_mins_sum__c = Decimal.valueOf(timeEntryDetail.time_totals.billable_mins_sum);
                        timeEntryObj.non_billable_mins_sum__c = Decimal.valueOf(timeEntryDetail.time_totals.non_billable_mins_sum);
                        timeEntryObj.Email__c = conObj.Email__c;
                        timeEntryObj.Date__c = lastday;
                        timeEntryObj.Time_Entry_ExternalId__c = lastdayStr+conObj.Teamwork_User_Id__c;
                        lstOfTimeEntry.add(timeEntryObj);
                    }
                }
            } catch(System.CalloutException e) {}
        }
        if(!lstOfTimeEntry.IsEmpty()){
            upsert lstOfTimeEntry Time_Entry_ExternalId__c;
        }
    }
    
    global void finish(Database.BatchableContext BC){}
}